### PR TITLE
Add dutch

### LINKED ISSUE #1: translations
There is a Json file with about 30 lines.
`https://github.com/funkyzooink/the-dragon-kid/blob/master/Resources/json/localization/en.json`

Translate to any language and add it to the localization folder as `countrycode.json`

### PR DESCRIPTION
**Pull request by bookmanindia**
Fixes #1

### CODE REVIEW

**Comment by funkyzooink** [comment]
Hi, there is two variables $value in the text that will be replaced in the game with a number. So it is needed to keep $value

**Comment by Ribiveer** [comment]
The Dutch translation here seems to have been done using Google Translate, as it doesn't make much sense.

**Comment by Ribiveer** [comment]
Looking closer, the Spanish one was made using an automatic translation as well.

**Comment by funkyzooink** [comment]
@Suhbahstiejaan thx for letting me know

**Pull request closed without merging**
